
include: package:flutter_lints/flutter.yaml

analyzer: 
  exclude: 
    - '**.config.dart'
    - '**.g.dart'
    - '**.gen.dart'
    - '**.freezed.dart'
  errors: 
    invalid_annotation_target: ignore

linter:
  rules:
    